import type { WordStudyEntry } from '../types';

function simpleHash(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
}

const GREEK_WORDS: Record<string, WordStudyEntry> = {
  man: {
    strongs: 'G444',
    language: 'Greek',
    lemma: 'ἄνθρωπος',
    transliteration: 'Anthropos',
    pronunciation: 'anth\'-ro-pos',
    gloss: 'Human / Man',
    definition: 'A human being, mankind, person of human nature.',
    triggers: ['man', 'men', 'human'],
  },
  pharisees: {
    strongs: 'G5330',
    language: 'Greek',
    lemma: 'Φαρισαῖος',
    transliteration: 'Pharisaios',
    pronunciation: 'far-ee-sah\'-yos',
    gloss: 'Pharisee / Separate One',
    definition: 'A member of the Jewish religious sect strict in observing the law.',
    triggers: ['pharisees', 'pharisee'],
  },
  nicodemus: {
    strongs: 'G3530',
    language: 'Greek',
    lemma: 'Νικόδημος',
    transliteration: 'Nikodemos',
    pronunciation: 'nee-kod\'-ay-mos',
    gloss: 'Conqueror of the People',
    definition: 'Nicodemus, a Pharisee and ruler of the Jews (John 3).',
    triggers: ['nicodemus'],
  },
  ruler: {
    strongs: 'G757',
    language: 'Greek',
    lemma: 'ἄρχων',
    transliteration: 'Archon',
    pronunciation: 'ar\'-khon',
    gloss: 'Ruler / Magistrate',
    definition: 'A chief officer, ruler, commander, or leader of the people.',
    triggers: ['ruler', 'rulers', 'chief'],
  },
  jews: {
    strongs: 'G2453',
    language: 'Greek',
    lemma: 'Ἰουδαῖος',
    transliteration: 'Ioudaios',
    pronunciation: 'ee-oo-dah\'-yos',
    gloss: 'Jewish / Judean',
    definition: 'Belonging to Judea; a Judean or Jewish person.',
    triggers: ['jews', 'jew', 'jewish'],
  },
  jesus: {
    strongs: 'G2424',
    language: 'Greek',
    lemma: 'Ἰησοῦς',
    transliteration: 'Iesous',
    pronunciation: 'ee-ay-soos\'',
    gloss: 'Jesus / Jehovah is Salvation',
    definition: 'Jesus, the promised Messiah and Son of God.',
    triggers: ['jesus'],
  },
  night: {
    strongs: 'G3571',
    language: 'Greek',
    lemma: 'νύξ',
    transliteration: 'Nux',
    pronunciation: 'nookse',
    gloss: 'Night Time',
    definition: 'Night; literal night or spiritual darkness.',
    triggers: ['night'],
  },
  rabbi: {
    strongs: 'G4461',
    language: 'Greek',
    lemma: 'ῥαββί',
    transliteration: 'Rhabbi',
    pronunciation: 'hrab-bee\'',
    gloss: 'My Master / Teacher',
    definition: 'An honorary title applied to Jewish teachers of the law.',
    triggers: ['rabbi'],
  },
  know: {
    strongs: 'G1492',
    language: 'Greek',
    lemma: 'εἴδω',
    transliteration: 'Eido',
    pronunciation: 'i\'-do',
    gloss: 'To Know / Perceive',
    definition: 'To see, know, understand, or perceive intuitively.',
    triggers: ['know', 'knew', 'knowing'],
  },
  teacher: {
    strongs: 'G1320',
    language: 'Greek',
    lemma: 'διδάσκαλος',
    transliteration: 'Didaskalos',
    pronunciation: 'dee-das\'-kah-los',
    gloss: 'Teacher / Instructor',
    definition: 'An instructor, teacher, or master of divine truth.',
    triggers: ['teacher', 'master'],
  },
  god: {
    strongs: 'G2316',
    language: 'Greek',
    lemma: 'θεός',
    transliteration: 'Theos',
    pronunciation: 'theh\'-os',
    gloss: 'God / Supreme Deity',
    definition: 'God, Supreme Ruler and Creator of the universe.',
    triggers: ['god', 'gods'],
  },
  born: {
    strongs: 'G1080',
    language: 'Greek',
    lemma: 'γεννάω',
    transliteration: 'Gennao',
    pronunciation: 'ghen-nah\'-o',
    gloss: 'To Be Born / Fathered',
    definition: 'To beget, bring forth, or be born anew spiritually.',
    triggers: ['born', 'begotten'],
  },
  again: {
    strongs: 'G509',
    language: 'Greek',
    lemma: 'ἄνωθεν',
    transliteration: 'Anothen',
    pronunciation: 'an\'-o-then',
    gloss: 'From Above / Anew',
    definition: 'From above, from heaven, or anew from the beginning.',
    triggers: ['again', 'above'],
  },
  water: {
    strongs: 'G5204',
    language: 'Greek',
    lemma: 'ὕδωρ',
    transliteration: 'Hudor',
    pronunciation: 'hoo\'-dor',
    gloss: 'Water',
    definition: 'Water; physical water or spiritual cleansing water of the Word.',
    triggers: ['water'],
  },
  spirit: {
    strongs: 'G4151',
    language: 'Greek',
    lemma: 'πνεῦμα',
    transliteration: 'Pneuma',
    pronunciation: 'pnyoo\'-mah',
    gloss: 'Spirit / Wind / Breath',
    definition: 'The Holy Spirit, human spirit, breath of life, or spiritual wind.',
    triggers: ['spirit', 'wind', 'breath'],
  },
  flesh: {
    strongs: 'G4561',
    language: 'Greek',
    lemma: 'σάρξ',
    transliteration: 'Sarx',
    pronunciation: 'sarks',
    gloss: 'Flesh / Human Body',
    definition: 'The physical body, human nature, or earthly frailty.',
    triggers: ['flesh'],
  },
  love: {
    strongs: 'G26',
    language: 'Greek',
    lemma: 'ἀγάπη',
    transliteration: 'Agapē',
    pronunciation: 'ah-gah\'--pay',
    gloss: 'Unconditional Love',
    definition: 'Divine, benevolent, self-sacrificial love of God.',
    triggers: ['love', 'loved', 'loving'],
  },
  world: {
    strongs: 'G2889',
    language: 'Greek',
    lemma: 'κόσμος',
    transliteration: 'Kosmos',
    pronunciation: 'kos\'-mos',
    gloss: 'World / Creation',
    definition: 'The created universe, earth, or humanity as the object of divine love.',
    triggers: ['world'],
  },
  son: {
    strongs: 'G5207',
    language: 'Greek',
    lemma: 'υἱός',
    transliteration: 'Huios',
    pronunciation: 'hwee-os\'',
    gloss: 'Son / Heir',
    definition: 'A son, descendant, or offspring in divine relationship.',
    triggers: ['son'],
  },
  believe: {
    strongs: 'G4100',
    language: 'Greek',
    lemma: 'πιστεύω',
    transliteration: 'Pisteuo',
    pronunciation: 'pis-tyoo\'-o',
    gloss: 'To Believe / Trust',
    definition: 'To place faith in, trust, or rely upon Christ.',
    triggers: ['believe', 'believeth', 'believed'],
  },
  life: {
    strongs: 'G2222',
    language: 'Greek',
    lemma: 'ζωή',
    transliteration: 'Zoē',
    pronunciation: 'dzoh-ay\'',
    gloss: 'Eternal Divine Life',
    definition: 'Life in the absolute sense, uncreated eternal life of God.',
    triggers: ['life'],
  },
  faith: {
    strongs: 'G4102',
    language: 'Greek',
    lemma: 'πίστις',
    transliteration: 'Pistis',
    pronunciation: 'pístis',
    gloss: 'Faith / Moral Conviction',
    definition: 'persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.',
    etymology: 'from G3982 (πείθω)',
    kjvUsage: 'assurance, belief, believe, faith, fidelity',
    triggers: ['faith'],
  },
  g3982: {
    strongs: 'G3982',
    language: 'Greek',
    lemma: 'πείθω',
    transliteration: 'Peitho',
    pronunciation: 'pi\'-tho',
    gloss: 'To Persuade / Trust',
    definition: 'To persuade, induce one by words to believe, have confidence, or obey.',
    etymology: 'from G4102 (πίστις)',
    kjvUsage: 'agree, assure, believe, have confidence, persuade, trust',
    triggers: ['g3982', 'peitho'],
  },
  word: {
    strongs: 'G3056',
    language: 'Greek',
    lemma: 'λόγος',
    transliteration: 'Logos',
    pronunciation: 'log\'-os',
    gloss: 'The Word / Divine Revelation',
    definition: 'The divine Word, expression of thought, or incarnate Son of God.',
    etymology: 'from G3004 (λέγω)',
    kjvUsage: 'account, cause, communication, doctrine, intent, news, word',
    triggers: ['word', 'words'],
  },
  city: {
    strongs: 'G4172',
    language: 'Greek',
    lemma: 'πόλις',
    transliteration: 'Polis',
    pronunciation: 'pol\'-is',
    gloss: 'City / Town',
    definition: 'Probably from the same as G4171, or perhaps from G4183; a town (properly with walls, of greater or less size): — city.',
    etymology: 'from G4171 (πόλεμος) or G4183 (πολύς)',
    kjvUsage: 'city (164), town (1)',
    triggers: ['city', 'cities', 'town'],
  },
  g4172: {
    strongs: 'G4172',
    language: 'Greek',
    lemma: 'πόλις',
    transliteration: 'Polis',
    pronunciation: 'pol\'-is',
    gloss: 'City / Town',
    definition: 'Probably from the same as G4171, or perhaps from G4183; a town (properly with walls, of greater or less size): — city.',
    etymology: 'from G4171 (πόλεμος) or G4183 (πολύς)',
    kjvUsage: 'city (164), town (1)',
    triggers: ['g4172', 'polis'],
  },
  g2031: {
    strongs: 'G4172',
    language: 'Greek',
    lemma: 'πόλις',
    transliteration: 'Polis',
    pronunciation: 'pol\'-is',
    gloss: 'City / Town',
    definition: 'Probably from the same as G4171, or perhaps from G4183; a town (properly with walls, of greater or less size): — city.',
    etymology: 'from G4171 (πόλεμος) or G4183 (πολύς)',
    kjvUsage: 'city (164), town (1)',
    triggers: ['g2031'],
  },
  king: {
    strongs: 'G935',
    language: 'Greek',
    lemma: 'βασιλεύς',
    transliteration: 'Basileus',
    pronunciation: 'bas-il-yoo\'s',
    gloss: 'King / Sovereign Leader',
    definition: 'A sovereign leader, king, prince, commander, or ruler of a kingdom.',
    etymology: 'from G939 (βάσις)',
    kjvUsage: 'king (115)',
    triggers: ['king', 'kings'],
  },
  kingdom: {
    strongs: 'G932',
    language: 'Greek',
    lemma: 'βασιλεία',
    transliteration: 'Basileia',
    pronunciation: 'bas-il-i\'-ah',
    gloss: 'Kingdom / Reign / Domain',
    definition: 'Royal power, reign, sovereign rule, or domain of a king; specifically the Kingdom of God.',
    etymology: 'from G935 (βασιλεύς)',
    kjvUsage: 'kingdom (162), reign (1)',
    triggers: ['kingdom', 'kingdoms'],
  },
  light: {
    strongs: 'G5457',
    language: 'Greek',
    lemma: 'φῶς',
    transliteration: 'Phos',
    pronunciation: 'foce',
    gloss: 'Light / Divine Illumination',
    definition: 'Light, truth, spiritual illumination, divine purity, and holy glory.',
    etymology: 'from G5316 (φαίνω)',
    kjvUsage: 'light (68), fire (2)',
    triggers: ['light', 'lights'],
  },
  heaven: {
    strongs: 'G3772',
    language: 'Greek',
    lemma: 'οὐρανός',
    transliteration: 'Ouranos',
    pronunciation: 'oo-ran-os\'',
    gloss: 'Heaven / Sky / Firmament',
    definition: 'The vaulted expanse of sky, atmosphere, starry heavens, or divine dwelling place of God.',
    etymology: 'perhaps from ὄρνυμι',
    kjvUsage: 'heaven (268), air (10), sky (5)',
    triggers: ['heaven', 'heavens', 'heavenly'],
  },
  earth: {
    strongs: 'G1093',
    language: 'Greek',
    lemma: 'γῆ',
    transliteration: 'Ge',
    pronunciation: 'ghay',
    gloss: 'Earth / Land / Ground',
    definition: 'Arable soil, ground, land, region, country, or the terrestrial earth as opposed to heaven.',
    etymology: 'from primary root',
    kjvUsage: 'earth (188), land (42), ground (18), country (2)',
    triggers: ['earth', 'land', 'ground'],
  },
  father: {
    strongs: 'G3962',
    language: 'Greek',
    lemma: 'πατήρ',
    transliteration: 'Pater',
    pronunciation: 'pat-ay\'r',
    gloss: 'Father / Ancestor / God the Father',
    definition: 'A father, progenitor, ancestor, originator, or God as Supreme Father of believers.',
    etymology: 'from primary root',
    kjvUsage: 'father (413)',
    triggers: ['father', 'fathers'],
  },
  lord: {
    strongs: 'G2962',
    language: 'Greek',
    lemma: 'κύριος',
    transliteration: 'Kurios',
    pronunciation: 'koo\'-ree-os',
    gloss: 'Lord / Sovereign Master',
    definition: 'One having supreme authority, sovereign Lord, Master, owner, title of Jesus Christ.',
    etymology: 'from κύρος (supreme authority)',
    kjvUsage: 'Lord (663), lord (72), master (11)',
    triggers: ['lord', 'lords', 'master'],
  },
  holy: {
    strongs: 'G40',
    language: 'Greek',
    lemma: 'ἅγιος',
    transliteration: 'Hagios',
    pronunciation: 'hag\'-ee-os',
    gloss: 'Holy / Sacred / Set Apart',
    definition: 'Sacred, holy, set apart for God, consecrated, pure, morally blameless.',
    etymology: 'from ἅγος (a feeling of awe)',
    kjvUsage: 'holy (161), saint (62)',
    triggers: ['holy', 'holiness', 'saint', 'saints'],
  },
  glory: {
    strongs: 'G1391',
    language: 'Greek',
    lemma: 'δόξα',
    transliteration: 'Doxa',
    pronunciation: 'dox\'-ah',
    gloss: 'Glory / Splendor / Honor',
    definition: 'Glory, majesty, divine radiance, splendor, honor, and exalted praise.',
    etymology: 'from G1380 (δοκέω)',
    kjvUsage: 'glory (145), honor (6), praise (4)',
    triggers: ['glory', 'glorious'],
  },
};

const HEBREW_WORDS: Record<string, WordStudyEntry> = {
  beginning: {
    strongs: 'H7225',
    language: 'Hebrew',
    lemma: 'רֵאשִׁית',
    transliteration: 'Reshith',
    pronunciation: 'ray-sheeth\'',
    gloss: 'Beginning / First Fruits / Chief',
    definition: 'First, beginning, best, chief part, time of commencement, or principal element.',
    etymology: 'from the same as H7218 (רֹאשׁ)',
    kjvUsage: 'beginning (50), chief (10), firstfruits (5)',
    triggers: ['beginning', 'beginnings', 'firstfruits', 'h7225'],
  },
  h7225: {
    strongs: 'H7225',
    language: 'Hebrew',
    lemma: 'רֵאשִׁית',
    transliteration: 'Reshith',
    pronunciation: 'ray-sheeth\'',
    gloss: 'Beginning / First Fruits / Chief',
    definition: 'First, beginning, best, chief part, time of commencement, or principal element.',
    etymology: 'from the same as H7218 (רֹאשׁ)',
    kjvUsage: 'beginning (50), chief (10), firstfruits (5)',
    triggers: ['h7225'],
  },
  created: {
    strongs: 'H1254',
    language: 'Hebrew',
    lemma: 'בָּרָא',
    transliteration: 'Bara',
    pronunciation: 'baw-raw\'',
    gloss: 'To Create / Shape / Form',
    definition: 'To create, shape, form out of nothing; specifically divine creation ex nihilo.',
    etymology: 'primitive root',
    kjvUsage: 'create (42), creator (3), make (2)',
    triggers: ['created', 'create', 'creator', 'creation', 'h1254'],
  },
  h1254: {
    strongs: 'H1254',
    language: 'Hebrew',
    lemma: 'בָּרָא',
    transliteration: 'Bara',
    pronunciation: 'baw-raw\'',
    gloss: 'To Create / Shape / Form',
    definition: 'To create, shape, form out of nothing; specifically divine creation ex nihilo.',
    etymology: 'primitive root',
    kjvUsage: 'create (42), creator (3), make (2)',
    triggers: ['h1254'],
  },
  god: {
    strongs: 'H430',
    language: 'Hebrew',
    lemma: 'אֱלֹהִים',
    transliteration: 'Elohim',
    pronunciation: 'el-o-heem\'',
    gloss: 'God / Supreme Creator',
    definition: 'God, Supreme Deity, Creator of heaven and earth, showing divine majesty and power.',
    etymology: 'plural of H433 (אֱלוֹהַּ)',
    kjvUsage: 'God (2346), god (244), judge (5)',
    triggers: ['god', 'gods', 'h430'],
  },
  h430: {
    strongs: 'H430',
    language: 'Hebrew',
    lemma: 'אֱלֹהִים',
    transliteration: 'Elohim',
    pronunciation: 'el-o-heem\'',
    gloss: 'God / Supreme Creator',
    definition: 'God, Supreme Deity, Creator of heaven and earth, showing divine majesty and power.',
    etymology: 'plural of H433 (אֱלוֹהַּ)',
    kjvUsage: 'God (2346), god (244), judge (5)',
    triggers: ['h430'],
  },
  heaven: {
    strongs: 'H8064',
    language: 'Hebrew',
    lemma: 'שָׁמַיִם',
    transliteration: 'Shamayim',
    pronunciation: 'shaw-mah\'-yim',
    gloss: 'Heavens / Sky / Expanse',
    definition: 'Dual of an unused singular; the visible heavens, sky, atmosphere, or abode of God.',
    etymology: 'from an unused root meaning to be lofty',
    kjvUsage: 'heaven (398), heavens (21), air (21)',
    triggers: ['heaven', 'heavens', 'sky', 'h8064'],
  },
  h8064: {
    strongs: 'H8064',
    language: 'Hebrew',
    lemma: 'שָׁמַיִם',
    transliteration: 'Shamayim',
    pronunciation: 'shaw-mah\'-yim',
    gloss: 'Heavens / Sky / Expanse',
    definition: 'Dual of an unused singular; the visible heavens, sky, atmosphere, or abode of God.',
    etymology: 'from an unused root meaning to be lofty',
    kjvUsage: 'heaven (398), heavens (21), air (21)',
    triggers: ['h8064'],
  },
  earth: {
    strongs: 'H776',
    language: 'Hebrew',
    lemma: 'אֶרֶץ',
    transliteration: 'Eretz',
    pronunciation: 'eh\'-rets',
    gloss: 'Earth / Land / Ground',
    definition: 'From an unused root probably meaning to be firm; the earth, land, country, or ground.',
    etymology: 'from an unused root',
    kjvUsage: 'land (1543), earth (712), country (140), ground (98)',
    triggers: ['earth', 'land', 'ground', 'h776'],
  },
  h776: {
    strongs: 'H776',
    language: 'Hebrew',
    lemma: 'אֶרֶץ',
    transliteration: 'Eretz',
    pronunciation: 'eh\'-rets',
    gloss: 'Earth / Land / Ground',
    definition: 'From an unused root probably meaning to be firm; the earth, land, country, or ground.',
    etymology: 'from an unused root',
    kjvUsage: 'land (1543), earth (712), country (140), ground (98)',
    triggers: ['h776'],
  },
  light: {
    strongs: 'H216',
    language: 'Hebrew',
    lemma: 'אוֹר',
    transliteration: 'Or',
    pronunciation: 'ore',
    gloss: 'Light / Dawn / Illumination',
    definition: 'Light, morning light, sun light, or spiritual illumination.',
    etymology: 'from H215 (אוֹר)',
    kjvUsage: 'light (114), day (2), bright (1)',
    triggers: ['light', 'lights', 'h216'],
  },
  h216: {
    strongs: 'H216',
    language: 'Hebrew',
    lemma: 'אוֹר',
    transliteration: 'Or',
    pronunciation: 'ore',
    gloss: 'Light / Dawn / Illumination',
    definition: 'Light, morning light, sun light, or spiritual illumination.',
    etymology: 'from H215 (אוֹר)',
    kjvUsage: 'light (114), day (2), bright (1)',
    triggers: ['h216'],
  },
  darkness: {
    strongs: 'H2822',
    language: 'Hebrew',
    lemma: 'חֹשֶׁךְ',
    transliteration: 'Choshek',
    pronunciation: 'kho-shek\'',
    gloss: 'Darkness / Obscurity / Night',
    definition: 'Darkness, literal night, obscurity, or spiritual blindness.',
    etymology: 'from H2821 (חָשַׁךְ)',
    kjvUsage: 'darkness (77), dark (2), obscurity (1)',
    triggers: ['darkness', 'dark', 'h2822'],
  },
  h2822: {
    strongs: 'H2822',
    language: 'Hebrew',
    lemma: 'חֹשֶׁךְ',
    transliteration: 'Choshek',
    pronunciation: 'kho-shek\'',
    gloss: 'Darkness / Obscurity / Night',
    definition: 'Darkness, literal night, obscurity, or spiritual blindness.',
    etymology: 'from H2821 (חָשַׁךְ)',
    kjvUsage: 'darkness (77), dark (2), obscurity (1)',
    triggers: ['h2822'],
  },
  day: {
    strongs: 'H3117',
    language: 'Hebrew',
    lemma: 'יוֹם',
    transliteration: 'Yom',
    pronunciation: 'yome',
    gloss: 'Day / Time / Period',
    definition: 'Day, warm hours of daylight, 24-hour day, or specific age/time.',
    etymology: 'from an unused root meaning to be hot',
    kjvUsage: 'day (2008), time (64), today (41)',
    triggers: ['day', 'days', 'h3117'],
  },
  h3117: {
    strongs: 'H3117',
    language: 'Hebrew',
    lemma: 'יוֹם',
    transliteration: 'Yom',
    pronunciation: 'yome',
    gloss: 'Day / Time / Period',
    definition: 'Day, warm hours of daylight, 24-hour day, or specific age/time.',
    etymology: 'from an unused root meaning to be hot',
    kjvUsage: 'day (2008), time (64), today (41)',
    triggers: ['h3117'],
  },
  night: {
    strongs: 'H3915',
    language: 'Hebrew',
    lemma: 'לַיְלָה',
    transliteration: 'Layil',
    pronunciation: 'lah\'-yil',
    gloss: 'Night / Night-Season',
    definition: 'Night, night-season, hours of darkness.',
    etymology: 'from a root meaning to fold back',
    kjvUsage: 'night (227), season (4)',
    triggers: ['night', 'nights', 'h3915'],
  },
  h3915: {
    strongs: 'H3915',
    language: 'Hebrew',
    lemma: 'לַיְלָה',
    transliteration: 'Layil',
    pronunciation: 'lah\'-yil',
    gloss: 'Night / Night-Season',
    definition: 'Night, night-season, hours of darkness.',
    etymology: 'from a root meaning to fold back',
    kjvUsage: 'night (227), season (4)',
    triggers: ['h3915'],
  },
  water: {
    strongs: 'H4325',
    language: 'Hebrew',
    lemma: 'מַיִם',
    transliteration: 'Mayim',
    pronunciation: 'mah\'-yim',
    gloss: 'Water / Waters / Sea',
    definition: 'Water, waters of the sea, rivers, or primeval ocean deep.',
    etymology: 'dual of a primitive noun',
    kjvUsage: 'water (571), waters (12)',
    triggers: ['water', 'waters', 'h4325'],
  },
  h4325: {
    strongs: 'H4325',
    language: 'Hebrew',
    lemma: 'מַיִם',
    transliteration: 'Mayim',
    pronunciation: 'mah\'-yim',
    gloss: 'Water / Waters / Sea',
    definition: 'Water, waters of the sea, rivers, or primeval ocean deep.',
    etymology: 'dual of a primitive noun',
    kjvUsage: 'water (571), waters (12)',
    triggers: ['h4325'],
  },
  firmament: {
    strongs: 'H7549',
    language: 'Hebrew',
    lemma: 'רָקִיעַ',
    transliteration: 'Raqia',
    pronunciation: 'raw-kee\'-ah',
    gloss: 'Firmament / Expanse / Celestial Vault',
    definition: 'An expanse, celestial vault, visible arch of sky supporting upper waters.',
    etymology: 'from H7554 (רָקַע)',
    kjvUsage: 'firmament (17)',
    triggers: ['firmament', 'expanse', 'h7549'],
  },
  h7549: {
    strongs: 'H7549',
    language: 'Hebrew',
    lemma: 'רָקִיעַ',
    transliteration: 'Raqia',
    pronunciation: 'raw-kee\'-ah',
    gloss: 'Firmament / Expanse / Celestial Vault',
    definition: 'An expanse, celestial vault, visible arch of sky supporting upper waters.',
    etymology: 'from H7554 (רָקַע)',
    kjvUsage: 'firmament (17)',
    triggers: ['h7549'],
  },
  spirit: {
    strongs: 'H7307',
    language: 'Hebrew',
    lemma: 'רוּחַ',
    transliteration: 'Ruach',
    pronunciation: 'roo\'-akh',
    gloss: 'Spirit / Wind / Breath of God',
    definition: 'Spirit, wind, breath; the life-giving Spirit of Yahweh active in creation and renewal.',
    etymology: 'from H7306 (רִיחַ)',
    kjvUsage: 'Spirit (232), wind (92), breath (27)',
    triggers: ['spirit', 'wind', 'breath', 'h7307'],
  },
  h7307: {
    strongs: 'H7307',
    language: 'Hebrew',
    lemma: 'רוּחַ',
    transliteration: 'Ruach',
    pronunciation: 'roo\'-akh',
    gloss: 'Spirit / Wind / Breath of God',
    definition: 'Spirit, wind, breath; the life-giving Spirit of Yahweh active in creation and renewal.',
    etymology: 'from H7306 (רִיחַ)',
    kjvUsage: 'Spirit (232), wind (92), breath (27)',
    triggers: ['h7307'],
  },
  and: {
    strongs: 'H853',
    language: 'Hebrew',
    lemma: 'אֵת',
    transliteration: 'Eth',
    pronunciation: 'eth',
    gloss: 'Untranslated Mark of Direct Object / Conjunction',
    definition: 'Apparent accusative particle, untranslated in English or denoting "and/with"; sign of the direct object.',
    etymology: 'from H604 (אָנָה)',
    kjvUsage: 'untranslated (7000+), with, and',
    triggers: ['and', 'eth', 'h853'],
  },
  h853: {
    strongs: 'H853',
    language: 'Hebrew',
    lemma: 'אֵת',
    transliteration: 'Eth',
    pronunciation: 'eth',
    gloss: 'Untranslated Mark of Direct Object / Conjunction',
    definition: 'Apparent accusative particle, untranslated in English or denoting "and/with"; sign of the direct object.',
    etymology: 'from H604 (אָנָה)',
    kjvUsage: 'untranslated (7000+), with, and',
    triggers: ['h853'],
  },
  was: {
    strongs: 'H1961',
    language: 'Hebrew',
    lemma: 'הָיָה',
    transliteration: 'Hayah',
    pronunciation: 'haw-yaw\'',
    gloss: 'To Be / Exist / Become',
    definition: 'To be, exist, become, come to pass, happen, or take place.',
    etymology: 'primitive root',
    kjvUsage: 'was (1200+), be, become, came to pass',
    triggers: ['was', 'were', 'became', 'h1961'],
  },
  h1961: {
    strongs: 'H1961',
    language: 'Hebrew',
    lemma: 'הָיָה',
    transliteration: 'Hayah',
    pronunciation: 'haw-yaw\'',
    gloss: 'To Be / Exist / Become',
    definition: 'To be, exist, become, come to pass, happen, or take place.',
    etymology: 'primitive root',
    kjvUsage: 'was (1200+), be, become, came to pass',
    triggers: ['h1961'],
  },
  without: {
    strongs: 'H8414',
    language: 'Hebrew',
    lemma: 'תֹּהוּ',
    transliteration: 'Tohu',
    pronunciation: 'to\'-hoo',
    gloss: 'Formless / Void / Wilderness',
    definition: 'Formlessness, confusion, unformed void, wilderness, or empty waste.',
    etymology: 'from an unused root meaning to lie waste',
    kjvUsage: 'without form (10), waste (4), vanity (4)',
    triggers: ['without', 'formless', 'tohu', 'h8414'],
  },
  form: {
    strongs: 'H8414',
    language: 'Hebrew',
    lemma: 'תֹּהוּ',
    transliteration: 'Tohu',
    pronunciation: 'to\'-hoo',
    gloss: 'Formless / Void / Wilderness',
    definition: 'Formlessness, confusion, unformed void, wilderness, or empty waste.',
    etymology: 'from an unused root meaning to lie waste',
    kjvUsage: 'without form (10), waste (4), vanity (4)',
    triggers: ['form', 'formless'],
  },
  void: {
    strongs: 'H922',
    language: 'Hebrew',
    lemma: 'בֹּהוּ',
    transliteration: 'Bohu',
    pronunciation: 'bo\'-hoo',
    gloss: 'Void / Emptiness',
    definition: 'Emptiness, void, desolate, ruin.',
    etymology: 'from an unused root meaning to be empty',
    kjvUsage: 'void (3), emptiness (1)',
    triggers: ['void', 'bohu', 'h922'],
  },
  h922: {
    strongs: 'H922',
    language: 'Hebrew',
    lemma: 'בֹּהוּ',
    transliteration: 'Bohu',
    pronunciation: 'bo\'-hoo',
    gloss: 'Void / Emptiness',
    definition: 'Emptiness, void, desolate, ruin.',
    etymology: 'from an unused root meaning to be empty',
    kjvUsage: 'void (3), emptiness (1)',
    triggers: ['h922'],
  },
  upon: {
    strongs: 'H5921',
    language: 'Hebrew',
    lemma: 'עַל',
    transliteration: 'Al',
    pronunciation: 'al',
    gloss: 'Upon / Above / Over',
    definition: 'Preposition meaning upon, over, above, concerning, against.',
    etymology: 'from H5920 (עַל)',
    kjvUsage: 'upon (2000+), over, above',
    triggers: ['upon', 'over', 'h5921'],
  },
  face: {
    strongs: 'H6440',
    language: 'Hebrew',
    lemma: 'פָּנִים',
    transliteration: 'Panim',
    pronunciation: 'paw-neem\'',
    gloss: 'Face / Surface / Presence',
    definition: 'Plural of an unused singular; face, surface, presence, countenance.',
    etymology: 'from H6437 (פָּנָה)',
    kjvUsage: 'face (1000+), presence, surface',
    triggers: ['face', 'faces', 'surface', 'h6440'],
  },
  deep: {
    strongs: 'H8415',
    language: 'Hebrew',
    lemma: 'תְּהוֹם',
    transliteration: 'Tehom',
    pronunciation: 'teh-home\'',
    gloss: 'The Deep / Abyss / Primeval Ocean',
    definition: 'An abyss, primeval ocean, deep water, surging mass of water.',
    etymology: 'from H1949 (הוּם)',
    kjvUsage: 'deep (36), depths (19)',
    triggers: ['deep', 'depths', 'abyss', 'h8415'],
  },
  moved: {
    strongs: 'H7363',
    language: 'Hebrew',
    lemma: 'רָחַף',
    transliteration: 'Rachaph',
    pronunciation: 'raw-khaf\'',
    gloss: 'To Hover / Flutter / Move',
    definition: 'To hover, flutter, move gently, brood over as a bird over her young.',
    etymology: 'primitive root',
    kjvUsage: 'move (2), flutter (1)',
    triggers: ['moved', 'hovering', 'brooding', 'h7363'],
  },
  said: {
    strongs: 'H559',
    language: 'Hebrew',
    lemma: 'אָמַר',
    transliteration: 'Amar',
    pronunciation: 'aw-mar\'',
    gloss: 'To Say / Speak / Command',
    definition: 'To say, speak, utter, command, promise, or declare.',
    etymology: 'primitive root',
    kjvUsage: 'said (3000+), speak (500), command',
    triggers: ['said', 'say', 'spake', 'h559'],
  },
  h559: {
    strongs: 'H559',
    language: 'Hebrew',
    lemma: 'אָמַר',
    transliteration: 'Amar',
    pronunciation: 'aw-mar\'',
    gloss: 'To Say / Speak / Command',
    definition: 'To say, speak, utter, command, promise, or declare.',
    etymology: 'primitive root',
    kjvUsage: 'said (3000+), speak (500), command',
    triggers: ['h559'],
  },
  saw: {
    strongs: 'H7200',
    language: 'Hebrew',
    lemma: 'רָאָה',
    transliteration: 'Raah',
    pronunciation: 'raw-aw\'',
    gloss: 'To See / Perceive / Behold',
    definition: 'To see, perceive, behold, observe, consider, or discern.',
    etymology: 'primitive root',
    kjvUsage: 'see (900+), saw (500+), look (100)',
    triggers: ['saw', 'see', 'beheld', 'h7200'],
  },
  h7200: {
    strongs: 'H7200',
    language: 'Hebrew',
    lemma: 'רָאָה',
    transliteration: 'Raah',
    pronunciation: 'raw-aw\'',
    gloss: 'To See / Perceive / Behold',
    definition: 'To see, perceive, behold, observe, consider, or discern.',
    etymology: 'primitive root',
    kjvUsage: 'see (900+), saw (500+), look (100)',
    triggers: ['h7200'],
  },
  divided: {
    strongs: 'H914',
    language: 'Hebrew',
    lemma: 'בָּדַל',
    transliteration: 'Badal',
    pronunciation: 'baw-dal\'',
    gloss: 'To Divide / Separate / Sever',
    definition: 'To divide, separate, sever, distinguish, or set apart.',
    etymology: 'primitive root',
    kjvUsage: 'divide (25), separate (12), sever (3)',
    triggers: ['divided', 'divide', 'separated', 'h914'],
  },
  called: {
    strongs: 'H7121',
    language: 'Hebrew',
    lemma: 'קָרָא',
    transliteration: 'Qara',
    pronunciation: 'kaw-raw\'',
    gloss: 'To Call / Name / Summon',
    definition: 'To call, name, summon, proclaim, invite, or cry out.',
    etymology: 'primitive root',
    kjvUsage: 'call (500+), called (300+), named',
    triggers: ['called', 'call', 'named', 'h7121'],
  },
  made: {
    strongs: 'H6213',
    language: 'Hebrew',
    lemma: 'עָשָׂה',
    transliteration: 'Asah',
    pronunciation: 'aw-saw\'',
    gloss: 'To Make / Do / Fashion',
    definition: 'To do, make, fashion, accomplish, produce, or perform.',
    etymology: 'primitive root',
    kjvUsage: 'do (1300+), make (1000+), made',
    triggers: ['made', 'make', 'did', 'h6213'],
  },
  good: {
    strongs: 'H2896',
    language: 'Hebrew',
    lemma: 'טוֹב',
    transliteration: 'Tov',
    pronunciation: 'tobe',
    gloss: 'Good / Pleasant / Excellent',
    definition: 'Good, pleasant, agreeable, excellent, beautiful, joyful.',
    etymology: 'from H2895 (טוֹב)',
    kjvUsage: 'good (500+), better (70)',
    triggers: ['good', 'better', 'tov', 'h2896'],
  },
  law: {
    strongs: 'H8451',
    language: 'Hebrew',
    lemma: 'תּוֹרָה',
    transliteration: 'Torah',
    pronunciation: 'to-raw\'',
    gloss: 'Instruction / Law / Guidance',
    definition: 'Direction, instruction, divine law, and God\'s foundational teaching for life.',
    etymology: 'from H3384 (יָרָה)',
    kjvUsage: 'law (219), direction (3)',
    triggers: ['law', 'laws', 'torah', 'h8451'],
  },
  commandment: {
    strongs: 'H4687',
    language: 'Hebrew',
    lemma: 'מִצְוָה',
    transliteration: 'Mitzvah',
    pronunciation: 'mits-vaw\'',
    gloss: 'Commandment / Precept',
    definition: 'Commandment, precept, divine code of ordinance or law.',
    etymology: 'from H6680 (צָוָה)',
    kjvUsage: 'commandment (180), precepts (4)',
    triggers: ['commandment', 'commandments', 'mitzvah', 'h4687'],
  },
  covenant: {
    strongs: 'H1285',
    language: 'Hebrew',
    lemma: 'בְּרִית',
    transliteration: 'Berith',
    pronunciation: 'ber-eeth\'',
    gloss: 'Covenant / League / Pledge',
    definition: 'Covenant, solemn pledge, divine compact or treaty between God and man.',
    etymology: 'from H1262 (בָּרָה)',
    kjvUsage: 'covenant (264), league (17)',
    triggers: ['covenant', 'covenants', 'berith', 'h1285'],
  },
  mercy: {
    strongs: 'H7356',
    language: 'Hebrew',
    lemma: 'רַחֲמִים',
    transliteration: 'Rachamim',
    pronunciation: 'rakh-am-eem\'',
    gloss: 'Mercy / Tender Compassion',
    definition: 'Compassion, tender mercies, deep visceral affection and pity.',
    etymology: 'from H7355 (רָחַם)',
    kjvUsage: 'mercy (30), compassion (8)',
    triggers: ['mercy', 'mercies', 'compassion', 'h7356'],
  },
  grace: {
    strongs: 'H2580',
    language: 'Hebrew',
    lemma: 'חֵן',
    transliteration: 'Chen',
    pronunciation: 'khen',
    gloss: 'Favor / Grace / Acceptance',
    definition: 'Favor, grace, charm, acceptance, or unmerited goodwill.',
    etymology: 'from H2603 (חָנַן)',
    kjvUsage: 'grace (38), favor (26)',
    triggers: ['grace', 'favor', 'h2580'],
  },
  faith: {
    strongs: 'H530',
    language: 'Hebrew',
    lemma: 'אֱמוּנָה',
    transliteration: 'Emunah',
    pronunciation: 'em-oo-naw\'',
    gloss: 'Faithfulness / Firmness / Fidelity',
    definition: 'Firmness, fidelity, steadfastness, truth, and enduring trust.',
    etymology: 'from H529 (אֵמוּן)',
    kjvUsage: 'faithfulness (18), truth (13), faith (4)',
    triggers: ['faith', 'faithfulness', 'emunah', 'h530'],
  },
  love: {
    strongs: 'H157',
    language: 'Hebrew',
    lemma: 'אָהַב',
    transliteration: 'Ahav',
    pronunciation: 'aw-hav\'',
    gloss: 'To Love / Affection',
    definition: 'To love, have affection for, desire, or hold dear.',
    etymology: 'primitive root',
    kjvUsage: 'love (160+), loved (40+)',
    triggers: ['love', 'loved', 'loving', 'h157'],
  },
  truth: {
    strongs: 'H571',
    language: 'Hebrew',
    lemma: 'אֱמֶת',
    transliteration: 'Emeth',
    pronunciation: 'eh\'-meth',
    gloss: 'Truth / Certainty / Reliability',
    definition: 'Stability, certainty, truth, trustworthiness, and absolute reality.',
    etymology: 'contracted from H539 (אָמַן)',
    kjvUsage: 'truth (92), true (18), faithfully (5)',
    triggers: ['truth', 'true', 'emeth', 'h571'],
  },
  righteousness: {
    strongs: 'H6666',
    language: 'Hebrew',
    lemma: 'צְדָקָה',
    transliteration: 'Tsedaqah',
    pronunciation: 'tsed-aw-kaw\'',
    gloss: 'Righteousness / Justice / Rectitude',
    definition: 'Rightness, justice, moral rectitude, virtue, and right standing before God.',
    etymology: 'from H6663 (צָדַק)',
    kjvUsage: 'righteousness (120+), justice (30)',
    triggers: ['righteousness', 'righteous', 'justice', 'h6666'],
  },
  salvation: {
    strongs: 'H3444',
    language: 'Hebrew',
    lemma: 'יְשׁוּעָה',
    transliteration: 'Yeshua',
    pronunciation: 'yesh-oo\'-aw',
    gloss: 'Salvation / Deliverance / Victory',
    definition: 'Something saved, deliverance, victory, prosperity, and spiritual salvation.',
    etymology: 'from H3467 (יָשַׁע)',
    kjvUsage: 'salvation (65), help (4), deliverance (3)',
    triggers: ['salvation', 'deliverance', 'victory', 'yeshua', 'h3444'],
  },
  sin: {
    strongs: 'H2403',
    language: 'Hebrew',
    lemma: 'חַטָּאָה',
    transliteration: 'Chattah',
    pronunciation: 'khat-taw-aw\'',
    gloss: 'Sin / Offense / Guilt',
    definition: 'An offense, sin, habitual sinfulness, or sin-offering.',
    etymology: 'from H2398 (חָטָא)',
    kjvUsage: 'sin (182), sin offering (116)',
    triggers: ['sin', 'sins', 'sinful', 'h2403'],
  },
  glory: {
    strongs: 'H3519',
    language: 'Hebrew',
    lemma: 'כָּבוֹד',
    transliteration: 'Kavod',
    pronunciation: 'kaw-bode\'',
    gloss: 'Glory / Weight / Splendor',
    definition: 'Weight, glory, honor, splendor, abundance, and divine presence.',
    etymology: 'from H3513 (כָּבַד)',
    kjvUsage: 'glory (156), honor (32)',
    triggers: ['glory', 'splendor', 'kavod', 'h3519'],
  },
  praise: {
    strongs: 'H1984',
    language: 'Hebrew',
    lemma: 'הָלַל',
    transliteration: 'Halal',
    pronunciation: 'haw-lal\'',
    gloss: 'To Praise / Shine / Exult',
    definition: 'To shine, boast, celebrate, boast in Yahweh, or praise joyfully.',
    etymology: 'primitive root',
    kjvUsage: 'praise (110), glory (8), boast (7)',
    triggers: ['praise', 'praises', 'halal', 'h1984'],
  },
  priest: {
    strongs: 'H3548',
    language: 'Hebrew',
    lemma: 'כֹּהֵן',
    transliteration: 'Kohen',
    pronunciation: 'ko-hane\'',
    gloss: 'Priest / Chief Ruler',
    definition: 'A principal officer or priest ministering before God.',
    etymology: 'active participle of an unused root',
    kjvUsage: 'priest (700+), chief ruler (2)',
    triggers: ['priest', 'priests', 'kohen', 'h3548'],
  },
  prophet: {
    strongs: 'H5030',
    language: 'Hebrew',
    lemma: 'נָבִיא',
    transliteration: 'Navi',
    pronunciation: 'naw-bee\'',
    gloss: 'Prophet / Inspired Spokesman',
    definition: 'A spokesman, inspired speaker, prophet of God.',
    etymology: 'from H5012 (נָבָא)',
    kjvUsage: 'prophet (300+)',
    triggers: ['prophet', 'prophets', 'navi', 'h5030'],
  },
  king: {
    strongs: 'H4428',
    language: 'Hebrew',
    lemma: 'מֶלֶךְ',
    transliteration: 'Melech',
    pronunciation: 'meh\'-lek',
    gloss: 'King / Sovereign Ruler',
    definition: 'A king, royal leader, sovereign ruler.',
    etymology: 'from H4427 (מָלַךְ)',
    kjvUsage: 'king (2500+)',
    triggers: ['king', 'kings', 'melech', 'h4428'],
  },
  kingdom: {
    strongs: 'H4467',
    language: 'Hebrew',
    lemma: 'מַמְלָכָה',
    transliteration: 'Mamlakah',
    pronunciation: 'mam-law-kaw\'',
    gloss: 'Kingdom / Dominion / Reign',
    definition: 'Dominion, kingdom, realm, or royal sovereignty.',
    etymology: 'from H4427 (מָלַךְ)',
    kjvUsage: 'kingdom (170), realm (4)',
    triggers: ['kingdom', 'kingdoms', 'h4467'],
  },
  house: {
    strongs: 'H1004',
    language: 'Hebrew',
    lemma: 'בַּיִת',
    transliteration: 'Bayit',
    pronunciation: 'bah\'-yith',
    gloss: 'House / Household / Temple',
    definition: 'A house, dwelling place, home, temple, or family lineage.',
    etymology: 'from H1129 (בָּנָה)',
    kjvUsage: 'house (1900+), household (60)',
    triggers: ['house', 'houses', 'household', 'h1004'],
  },
  bread: {
    strongs: 'H3899',
    language: 'Hebrew',
    lemma: 'לֶחֶם',
    transliteration: 'Lechem',
    pronunciation: 'leh\'-khem',
    gloss: 'Bread / Food / Grain',
    definition: 'Bread, food, grain, or sustenance.',
    etymology: 'from H3898 (לָחַם)',
    kjvUsage: 'bread (290), food (20)',
    triggers: ['bread', 'food', 'lechem', 'h3899'],
  },
  way: {
    strongs: 'H1870',
    language: 'Hebrew',
    lemma: 'דֶּרֶךְ',
    transliteration: 'Derech',
    pronunciation: 'deh\'-rek',
    gloss: 'Way / Path / Journey / Manner',
    definition: 'A road, course of life, path, journey, or manner of living.',
    etymology: 'from H1869 (דָּרַךְ)',
    kjvUsage: 'way (600+), path (30)',
    triggers: ['way', 'ways', 'path', 'derech', 'h1870'],
  },
  life: {
    strongs: 'H2416',
    language: 'Hebrew',
    lemma: 'חַיִּים',
    transliteration: 'Chaim',
    pronunciation: 'khay-eem\'',
    gloss: 'Life / Living',
    definition: 'Life, living, age, lifetime, or fountain of life.',
    etymology: 'from H2421 (חָיָה)',
    kjvUsage: 'life (400+), living (100)',
    triggers: ['life', 'lives', 'living', 'h2416'],
  },
};

const OT_BOOKS = new Set([
  'Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy', 'Joshua', 'Judges', 'Ruth',
  '1 Samuel', '2 Samuel', '1 Kings', '2 Kings', '1 Chronicles', '2 Chronicles', 'Ezra',
  'Nehemiah', 'Esther', 'Job', 'Psalms', 'Proverbs', 'Ecclesiastes', 'Song of Solomon',
  'Isaiah', 'Jeremiah', 'Lamentations', 'Ezekiel', 'Daniel', 'Hosea', 'Joel', 'Amos',
  'Obadiah', 'Jonah', 'Micah', 'Nahum', 'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi'
]);

export function annotateTextWithStrongsSync(text: string, bookName?: string): Array<{ word: string; strongs?: WordStudyEntry }> {
  if (!text) return [];
  const isOT = bookName ? OT_BOOKS.has(bookName) : true;
  const tokens = text.split(/(\s+|[.,;:!?—–\-"'()]+)/);

  let wordIndex = 0;

  return tokens.map((token) => {
    const clean = token.replace(/[^a-zA-Z]/g, '').toLowerCase();
    if (clean.length < 1) {
      return { word: token };
    }

    const currentWordIndex = wordIndex;
    wordIndex++;

    // 1. Skip leading sentence connector "And" at the beginning of a verse (e.g. Gen 1:7 "And God said...")
    if (currentWordIndex === 0 && clean === 'and') {
      return { word: token };
    }

    if (isOT) {
      if (HEBREW_WORDS[clean]) {
        return { word: token, strongs: HEBREW_WORDS[clean] };
      }
      if (GREEK_WORDS[clean]) {
        return { word: token, strongs: GREEK_WORDS[clean] };
      }
    } else {
      if (GREEK_WORDS[clean]) {
        return { word: token, strongs: GREEK_WORDS[clean] };
      }
      if (HEBREW_WORDS[clean]) {
        return { word: token, strongs: HEBREW_WORDS[clean] };
      }
    }

    return { word: token };
  });
}
